export interface Trip {
  id: string;
  destination: string;
  startDate: string;
  endDate: string;
  selectedActivityIds: string[];
  scheduledActivities: ScheduledActivity[];
}

export type ActivityType = 'MUSEUM' | 'LANDMARK' | 'PARK' | 'RESTAURANT' | 'SHOPPING' | 'ENTERTAINMENT';

export interface Activity {
  id: string;
  name: string;
  description: string;
  city: string;
  latitude: number;
  longitude: number;
  typicalDuration: number;
  priority: number;
  activityType: ActivityType;
  bestTimeOfDay: string | null;
}

export interface ScheduledActivity {
  id?: string;  // Optional because it will be generated by Prisma
  day: number;
  order: number;
  tripId: string;
  activityId: string;
  activity: Activity;
}